- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-20221122091720947800000010.ctv3lq0mxvbe.us-east-2.rds.amazonaws.com"
    login_user: "cynthia"
    login_password: "devopspblproject"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-20221122091720947800000010.ctv3lq0mxvbe.us-east-2.rds.amazonaws.com" }
    - { regexp: '^admin', line: "cynthia" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "cynthiasproject" }


